### ISSUE TITLE
Create SQL database and tables

### ISSUE THREAD

**Issue by dantstephens** [deuce-shaw/Project3#9]
User story:

As a database user, I need cleaned data loaded into my database so that I can use it.

### Acceptance criteria:

- Code is create in Python and can be ran in-line
- 6 tables with keys and constraints matching ERD are created

### Dependency:

- [x]  Work in ticket #6 must be completed before beginning this work
- [x]  Work in ticket #7 must be completed before beginning this work
- [x] Work in ticket #8  must be completed before beginning this work

**Comment by HMills76** [comment]
Created the pythonsqlite.db, created tables subject, race, ethnicity, asthma, rhinitis and dermatitis.  Load data from the individual csv files into their corresponding tables.  Verified that the tables were created and that the data was imported. Closed the connection to the database.
